config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root to: "pages#index"
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      ContactMailer.send_when_admin_reply(@contact).deliver
      flash[:success] = 'お問い合わせを受け付けました'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<h1>投稿完了</h1>

app/views/contacts/new.html.erb
<%= form_with model: @contact,local: true do |f| %>

  <div class="form-group">
    <%= f.label :email, '返信先メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

 <div class="form-group">
   <%= f.label :message, 'お問い合わせ内容' %>
   <%= f.text_area :message, size: '10x10', class: 'form-control' %>
 </div>

  <%= f.submit '送信' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstPage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="py-4">
      <div class="container text-center">
        <h1><%= link_to root_path do %><%= image_tag "logo.png" %><% end %></h1>
      </div>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
        <div class="container">
          <%= link_to root_path do %><div class="navbar-brand">FIRSTPAGE COMPANY</div><% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbar-content"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbar-content">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to root_path do %><div class="nav-link">Top</div><% end %>
          </li>
          <li class="nav-item">
            <%= link_to "#" do %><div class="nav-link">Project</div><% end %>
          </li>
          <li class="nav-item">
            <%= link_to "#" do %><div class="nav-link">Company</div><% end %>
          </li>
          <li class="nav-item">
            <%= link_to "#" do %><div class="nav-link">Recruit</div><% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to new_contact_path do %><div class="nav-link ">Contact</div><% end %>
          </li>
        </ul>
      </div>
      </nav>
    </header>
    <%= yield %>

  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">１列目</div>
    <div class="col-5">２列目</div>
    <div class="col-5">３列目</div>
  </div>

  <div class="row">bbbb</div>
</div>